### ISSUE TITLE
How to get official .describe() metadata?

### ISSUE THREAD

**Issue by tkirschke** [singer-io/tap-salesforce#111]
Hi everyone,
I am wondering if you can use the salesforce tap to additionally also get an objects metadata. With metadata, I mean the data I get, shown on [this page](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_describe.htm) . If it is already possible with this tap, please let me know how.

**Comment by dmosorast** [comment]
Hello @tkirschke! The tap does not emit the metadata as a stream, but it does have code request it during discovery to find all objects available to the given credentials in the config file.

If you're looking for example code to work this up yourself and retrieve just the specific metadata you need, you can see how it makes the request [here](https://github.com/singer-io/tap-salesforce/blob/e72e0e8038ca10a6be9267fab68aba6de8ba162f/tap_salesforce/salesforce/__init__.py#L330-L346)

**Comment by tkirschke** [comment]
Hi @dmosorast , thanks for your fast reply!
I will now try to modify the tap, so I can pass the .describe() data as a stream. Might reach out to you again if I run into some problems :)
