### ISSUE TITLE
Validate start_date is a timestamp and parse select_fields_by_default properly

### ISSUE THREAD

**Issue by KAllan357** [singer-io/tap-salesforce#26]
Salesforce SOQL queries will fail if `start_date` is simply a date and not a date with a timestamp.

We currently check `select_fields_by_default` against the string `"true"` - this can lead to unexpected behavior.

* Update the readme to reflect the timestamp
* Improve parsing of  `select_fields_by_default`.
* Look into validating Config file (singer-python?)

**Comment by ps2goat** [comment]
This looks like it can be closed, too. I think with my past experience, Salesforce only shows DateTimes to the second in the GUI, but they are stored to the millisecond. `2018-01-08T00:00:00.000Z`
