### ISSUE TITLE
Getting 400 Client Error: Bad Request for url: https://test.salesforce.com/services/oauth2/token

### ISSUE THREAD

**Issue by kaverimaniant** [singer-io/tap-salesforce#46]
Here is my config.json file (I didn't disclose my client id, secret and token values but I know it is working with another .NET app). When I try to run "tap-salesforce --config config.json", it is showing the error
400 Client Error: Bad Request for url: https://test.salesforce.com/services/oauth2/token

{
  "client_id": "client_id_value",
  "client_secret": "client_secret",
  "refresh_token": "token_value",
  "start_date": "2018-03-03T00:00:00Z",
  "api_type": "BULK",
  "select_fields_by_default": true,
  "is_sandbox": true
}

**Comment by kaverimaniant** [comment]
Thank you. I solved it myself.

**Comment by KAllan357** [comment]
:+1:

**Comment by sokser** [comment]
@kaverimaniant what was the solution to this?
