### ISSUE TITLE
Increase Salesforce API version to >= 43.0

### ISSUE THREAD

**Issue by stkbailey** [singer-io/tap-salesforce#79]
I wanted to inquire what it would take to bump up the Salesforce API version for the tap, and what sort of testing would be required?

I am running into some issues specifically with the `ForecastingQuota` object, where API v41.0 does not return quota for Territory-based forecasts. Probably an edge case for most people, but it would be useful for me, so I thought I'd ask.

For reference, here are the API release versions:

> API Version 49.0 = Summer '20
> API Version 48.0 = Spring '20
> API Version 47.0 = Winter '20
> API Version 46.0 = Summer '19
> API Version 45.0 = Spring '19
> API Version 44.0 = Winter '19
> API Version 43.0 = Summer '18

From: https://help.salesforce.com/articleView?id=000334996&type=1&mode=1

**Comment by camerondavison** [comment]
I was unable to use any of the new `InsurancePolicy` `sobjects` that have ben added recently.

**Comment by dsprayberry** [comment]
This was addressed via [PR 116](https://github.com/singer-io/tap-salesforce/pull/116).
