### ISSUE TITLE
how is state persisted?

### ISSUE THREAD

**Issue by ps2goat** [singer-io/tap-salesforce#88]
Are users meant to just update the start_date in the config file for the next run? It isn't 100% clear without digging into the code. One of the Singer targets I looked at has examples of persisting state to a file. The README for this project only mentions how to _consume_ an existing state file.

**Comment by dsprayberry** [comment]
See: https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md#running-a-singer-tap-with-a-singer-target
