### ISSUE TITLE
Infinite Login Token Refresh

### ISSUE THREAD

**Issue by andyoneal** [singer-io/tap-salesforce#93]
I think I'm hitting a race condition with login_timer. My sync happened to finish in almost exactly 30min, which caused the timer to be canceled while sf.login() has already started on the separate timer thread, but had not yet completed because of the backoff delay. Since the timer was not correctly cancelled, the tap will continuously refresh the token every 15min until is it manually killed.

In the log below, you can see sf.login() running from 21:30:45,288Z to 21:30:47,072Z. I don't know enough about backoff and threading to know if the failure only occurs if the sync finishes during the backoff or if it can occur anywhere in that ~2 sec window before login_timer.start()

Here's the snippet from the log:

> 2020-12-30 21:30:45,288Z    tap - INFO Attempting login via OAuth2
> 2020-12-30 21:30:45,288Z    tap - INFO Making POST request to https://login.salesforce.com/services/oauth2/token with body {'client_id': '.....................................................................................', 'refresh_token': '.......................................................................................', 'client_secret': '...................', 'grant_type': 'refresh_token'}
> 2020-12-30 21:30:45,290Z    tap - ERROR Backing off _make_request(...) for 1.7s (requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
> 2020-12-30 21:30:45,290Z    tap - INFO ConnectionError detected, triggering backoff: 1 try
> <..snip....>
> 2020-12-30 21:30:46,903Z    tap - INFO dsfs__DocuSign_Status__History: Completed sync (0 rows)
> 2020-12-30 21:30:46,903Z    tap - INFO Finished sync
> 2020-12-30 21:30:47,005Z    tap - INFO Making POST request to https://login.salesforce.com/services/oauth2/token with body {'client_id': '.....................................................................................', 'refresh_token': '.......................................................................................', 'client_secret': '...................', 'grant_type': 'refresh_token'}
> 2020-12-30 21:30:47,072Z    tap - INFO OAuth2 login successful
> 2020-12-30 21:30:47,072Z    tap - INFO Starting new login timer
> 2020-12-30 21:45:47,073Z    tap - INFO Attempting login via OAuth2
> 2020-12-30 21:45:47,073Z    tap - INFO Making POST request to https://login.salesforce.com/services/oauth2/token with body {'client_id': '.....................................................................................', 'refresh_token': '.......................................................................................', 'client_secret': '...................', 'grant_type': 'refresh_token'}
> 2020-12-30 21:45:47,075Z    tap - ERROR Backing off _make_request(...) for 1.2s (requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
> 2020-12-30 21:45:47,075Z    tap - INFO ConnectionError detected, triggering backoff: 1 try
> 2020-12-30 21:45:48,237Z    tap - INFO Making POST request to https://login.salesforce.com/services/oauth2/token with body {'client_id': '.....................................................................................', 'refresh_token': '.......................................................................................', 'client_secret': '...................', 'grant_type': 'refresh_token'}
> 2020-12-30 21:45:48,311Z    tap - INFO OAuth2 login successful
> 2020-12-30 21:45:48,311Z    tap - INFO Starting new login timer
> 2020-12-30 22:00:48,316Z    tap - INFO Attempting login via OAuth2
> 2020-12-30 22:00:48,316Z    tap - INFO Making POST request to https://login.salesforce.com/services/oauth2/token with body {'client_id': '.....................................................................................', 'refresh_token': '.......................................................................................', 'client_secret': '...................', 'grant_type': 'refresh_token'}
> 2020-12-30 22:00:48,317Z    tap - ERROR Backing off _make_request(...) for 1.2s (requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
> 2020-12-30 22:00:48,317Z    tap - INFO ConnectionError detected, triggering backoff: 1 try
> 2020-12-30 22:00:49,494Z    tap - INFO Making POST request to https://login.salesforce.com/services/oauth2/token with body {'client_id': '.....................................................................................', 'refresh_token': '.......................................................................................', 'client_secret': '...................', 'grant_type': 'refresh_token'}
> 2020-12-30 22:00:49,593Z    tap - INFO OAuth2 login successful
> 2020-12-30 22:00:49,593Z    tap - INFO Starting new login timer
> <...continues for hours...>

**Comment by AustinBGibbons** [comment]
We're having the same issue as of this weekend, even after refreshing the salesforce login in the stitch settings page.

**Comment by dsprayberry** [comment]
This was addressed via [PR 114](https://github.com/singer-io/tap-salesforce/pull/114). Are either of you still encountering this @andyoneal @AustinBGibbons ?

**Comment by andyoneal** [comment]
No, haven't seen this happen in a long time. Looks like its fixed.
